spring:
  application:
    name: sender-service
  rabbitmq:
    port: 5672
    host: rabbitmq
    username: guest
    password: guest
    virtual-host: /

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
  endpoint:
    metrics:
      enabled: 'true'
  server:
    port: '8080'
  prometheus:
    metrics:
      export:
        enabled: 'true'