spring:

  application:
    name: collector-service

server:
  port: 8082

recipient:
  api:
    url: ${MICRO_RECIPIENT_URL:http://localhost:8081}
  scheduler:
    interval: 30

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
  endpoint:
    metrics:
      enabled: 'true'
  server:
    port: '8082'
  prometheus:
    metrics:
      export:
        enabled: 'true'
