spring:
  application:
    name: recipient-service
  rabbitmq:
    port: 5672
    host: rabbitmq
    username: guest
    password: guest
    virtual-host: /

server:
  port: 8081

recipient:
  scheduler:
    interval: 5

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
  endpoint:
    metrics:
      enabled: 'true'
  server:
    port: '8081'
  prometheus:
    metrics:
      export:
        enabled: 'true'